### ISSUE TITLE
.non sessions to .ardour conversion: workarounds + note on website FAQ?

### ISSUE THREAD

**Issue by marttt** [original-male/non#157]
Hi, I apologize for asking this here since it's not a direct issue. But:
Can you suggest any workarounds for converting .non sessions back to .ardour (and retaining region splits and placement on multiple tracks)?

I'm really fascinated by the simplicity of non-timeline (and, as an Arch Linux user, I also love the general philosophy behind the suite). Unfortunately I have to hand over my work (radio talk shows) to a producer who uses Pro Tools. So far I've edited with Reaper and made conversions with AATranslator (excellent software that works very well under Linux+Wine), but I'd really love to switch over to non-daw completely. (Thus, the conversion workflow would be .non -> .ardour -> .ptf with AATranslator)

Also, it would be good (for non-technical users like me) to briefly explain on the website/FAQ why importing from Ardour is possible but exporting to Ardour isn't.

Thanks for thinking along, I really admire what you've done with this suite.

**Comment by original-male** [comment]
Workaround:

Create an export track (preferably well named!) for every track that you want to export unmixed, and connect the them to the tracks you want to export. Do a freewheeling record of onto these loop-backed tracks, and then you can find the .wav files in the non-timeline project directory. These should be fairly easy to import into Ardour or any other DAW (one wave per track). For Ardour, you might actually need to do one wave per channel, because the last time I checked Ardour couldn't do multi-channel files (maybe it can import them though?)

If you're passing this to someone who uses ProTools, I would just give them the exported waves directly and let them drop them into ProTools themeselves... No need for Ardour.

A generic DAW interchange format is, unfortunately, still a pipe dream.

As for an explanation: 

Non is free-software. I wrote it to meet my own needs and share it out of the goodness of my heart. I had some very old Ardour sessions that I needed to convert, and so I wrote a tool to do that. I have never had a need to convert sessions back to Ardour format, so I didn't write a tool to do that. It's that simple. 

Likewise, I didn't write a tool to import from ProTools or any other DAWs because I have no need to do so.

On the technical side, Non-timeline can do some things that Ardour can't, clip-wise (region looping in particular), and it's not quite trivial to translate between the two (especially in a way that is guaranteed to produce the exact same audio output). An exporter to Ardour would have to deal with that. 

The best way to guarantee everything (audio) goes from one DAW to another is to just export the individual tracks as I described above---this applies to every DAW and even to the situation of importing to Non-Timeline from Ardour.

**Comment by marttt** [comment]
Excellent explanations, thanks very much. You could add some of this to the
web page as well, though.

But: the problem is, my producer needs to modify the montage files (maybe
shift some of my splitting points backwards or forwards in Pro Tools etc).
So the wave export doesn't help here unfortunately. I need to hand over the
montage session and the initial audio files in full length.

Maybe the guy behind AATranslator would find time looking into the .non >
.ardour/etc conversion. :-) He's done awesome work thus far:
http://www.aatranslator.com.au/

I guess I'll bother him with this if I dare.

Once again, for an one-man hobby project non-daw is really impressive.
Cheers and keep going!

**Comment by original-male** [comment]
What would I say on the webpage though? There's no philosophical reason for exporters to formats not to be implemented.

What project formats does Ardour import/export? Does the Ardour website explain why it doesn't implement what it doesn't implement?

I see. Well, yeah, there's no way to get that level of control with just wave files. Do you know if there's a simpler format the Ardour and/or ProTools can import? 

The Ardour format has a lot of random stuff in it, and a lot of indirection which would make generating it a bit tedious. I have no idea what elements are required---it seems like they all appear in the saved projects whether those features are used or not.

The two main obstacles that come to mind when converting from non-timeline to Ardour are the region looping (not so hard, every repeat just needs to be calculated and converted into a separate region in the output) and fade outs/ins. Fades in Ardour are treated as separate objects IIRC. The Ardour project importer doesn't attempt to convert fades for this reason. If you don't use these features in your sessions, then you may not care these issues.

Since this is something that you're concerned about and interested in, I think you are probably the best person for the job. The Non and Ardour formats at least, are basically just text files. You could write a converter in any language. And since you're going from Non to Ardour, you wouldn't even have to deal with parsing XML.

**Comment by marttt** [comment]
I wrote a rudimentary Non --> Samplitude EDL converter:
http://tihnik.sdf.org/s/non/non2edl

It's ugly and it only transfers region placement on a single track
with a single audio file (which was my essential need).
Fades, volume envelopes etc are all zeroed out.

The resulting 'snapshot.edl' file can then be converted to many major
DAWs with AATranslator [1]. (Fascinating piece of Windows shareware
with a really nice developer; I think it also works fine under Wine.)

So, using this pipeline -- non2edl | AATranslator --
I painlessly converted my Timeline session to Pro Tools 7!

(And thus I can confirm that Non has been used to produce at least one
50-minute broadcast to 'Radio Night University', a landmark weekly
series of radio lectures aired in Estonian Public Broadcasting. [2])

During the montage I wrote a bunch of other a-few-liners as well, to
modify and analyze Non's sessions. The AWKability of the format is
absolutely wonderful. Thanks a lot for your work, Mr Liles!

1: http://www.aatranslator.com.au
2: http://www.ylikool.ee
