### ISSUE TITLE
Exporting audio

### ISSUE THREAD

**Issue by PaulBatchelor** [original-male/non#209]
How does one export audio from Non? I've been having trouble figuring that out.

Thanks,

-Paul

**Comment by original-male** [comment]
You just record the output with any JACK client, including Non-Timeline itself.

I usually just create a stereo track called Export and record the loopback output (from a Master strip in Non-Mixer) onto that. Then you can find the file called Export*.wav in the project's sources/ directory. Enable freewheeling mode before starting the recording for a faster export.

**Comment by PaulBatchelor** [comment]
Thanks! Never heard of freewheeling mode(!) Gonna have some fun with this :)

**Comment by Israel-** [comment]
Hi, I was hoping that there would be a more intuitive way to export audio.  It would be nice to export the audio track by track (I know each track is already exported to a wav file... but I am think of user friendly DAW).
The simple act of being able to export the track would be nice.  As well as making the mixer integrate more easily... I would like to use non-timeline for more than just creating the tracks that I need to import into a program that can easily handle these tasks.

**Comment by nico202** [comment]
@Israel- The very first time I tried it I thought that the export menu should have been added.
But I don't think it anymore. Adding an "export" feature just adds useless complexity to the software, while it takes a couple of actions to do it manually. Actions that you would need to do to "customize" the export, however. By doing the export "manually" (create a track, attach the needed sources, adjust volumes, arm record, freewheel, copy the file from the output directory) is just as easy as the "export menu" (export, starting point, stopping point, tracks wanted, output directory...), IMO.

**Comment by Israel-** [comment]
@nico202 This may be the case, but the user experience is the biggest issue.
There is no clear documentation within the program that explains how to do this process.
We users expect the software to behave in a certain way, and exporting the recorded audio is the primary reason to be using a DAW.
At very least I think the installed documentation should include a large bold section titled
 # Exporting Audio
That would include the step by step procedures.
This would, at least to me, close the actual issue described.
But, your method is the same as adding the feature for export, but unexpected and undocumented, but it is more work for the user, rather than the programmer.

I am very thankful that this program exists, it makes using an old computer possible to record high quality audio, which is impossible using anything else, and be able to customize my jack setup, and record multiple inputs simultaneously.  This is why I want it to become easier for users.

**Comment by nico202** [comment]
@Israel- about the documentation we had a discussion somewhere/some time ago about a "rewrite", keeping apart what is implemented and what is on the todo-list (something that on the actual documentation is not clear) and adding workflow examples. If you are interested we could revive this idea.
About the software itself, I think that adding `duplicate`  features is only going to make the program bloated like ardour is. And, it does not teach the user "how the things are working".

Obviously those are just opinions, but I'd prefer a good/up-to-date manual instead of blindly adding features.
```
But, your method is the same as adding the feature for export, but unexpected and undocumented, but it is more work for the user, rather than the programmer.
```
Here the work for the user is only apparent, the work for the programmer is not much, the need for it is something I feel it's not necessary

**Comment by original-male** [comment]
I agree with @nico202. But there's something else that has factored into my decision not to add an export dialog:

Think about how much time you spend working on a song. Arranging, recording, mixing, and then finally it's time to export, which you set up once and maybe do a couple of times, correcting problems. What is it? 1% of the time you spend working on the song? It's just not the kind of feature that needs to an optimized user experience, IMHO, especially since it's so (potentially) complicated due to the infinite possible arrangements of the JACK graph.

That being said, when this issue was opened I looked in the documentation for a link to the Export section to give to the OP, and didn't find anything... This process is perhaps obvious to long time JACK users, but I agree that a new user would have a hard time intuiting it and it needs to be documented (as does general track bouncing).

**Comment by PaulBatchelor** [comment]
@original-male Would it be possible to add such documentation about exporting? Even just the original sentence you supplied would suffice for now.

**Comment by Israel-** [comment]
@nico202 You make good points, but the main issue is the lack of clarity for the end user.
@original-male thank you for your very clear answer!
@PaulBatchelor I agree, this would make it easy for the end user.
