### ISSUE TITLE
NSM gui unresponsive

### ISSUE THREAD

**Issue by wwweeds** [original-male/non#217]
My NSM install is totally unresponsive and has grayed out buttons. I have tried installing this a few times with no luck. The rest of the non suite is functioning well, so I dont think its an issue with NTK. 

Running on Arch with all dependancies (I think). Any clues where to look for something missing?
![nsm no worky](https://user-images.githubusercontent.com/8131685/27060038-c293309a-4fc9-11e7-8b06-36f90b285507.png)

**Comment by original-male** [comment]
In order for liblo/OSC to work, which NSM needs, you have to have a sane networking setup, where your hostname resolves to an IP address. This usually means having an appropriate entry in /etc/hosts, unless you're running a DNS sever.

This is taken care of for you on most distros, but may not be on Arch.

**Comment by original-male** [comment]
an example /etc/hosts entry would look like:

`127.0.0.1 localhost`
`127.0.0.1 YOUR_HOSTNAME_HERE`

Where YOUR_HOSTNAME_HERE is the same value that's in /etc/hostname

**Comment by wwweeds** [comment]
Perfect, that solved it!

**Comment by NexAdn** [comment]
I just had the same problem, but I had my hostname (`archer`) already set in `/etc/hosts`. But this didn't work out well. The reason for that might have been that the IPv4 reverse DNS pointed to a different hostname (`n017`), due to the computer being in a larger campus network.

The solution was to add the exact record (i.e. FQDN) the reverse DNS offers for the IPv4 address to `/etc/hosts` so that it resolves to `127.0.0.1` and `::1` like this:

```
127.0.0.1 n017.my.domain
::1       n017.my.domain
```

OS: Gentoo Linux with OpenRC
Network is managed via netifrc, `/etc/resolv.conf` contains the campus network's nameserves and the campus network's domain as received via DHCPv4/RA.
