### ISSUE TITLE
[non-session-manager] Export option directly in the GUI

### ISSUE THREAD

**Issue by diovudau** [original-male/non#240]
For convenience: Add an export button to the GUI that asks for a filename and then does the tar -h thing.

**Comment by grammoboy2** [comment]
As a user, i don't see the need for this tbh. Wouldn't it make the gui more complex?

You can tar what you want using the command line or using your filemanager.

**Comment by falkTX** [comment]
That are quite some steps compared to just have the option in the GUI, for convenience.
Also reduces human error, since you could be archiving:
1. in a bad way (zip files do not support symlinks, for example, which can break projects)
2. the wrong folder (if you have multiple ones named in a similar way)

**Comment by grammoboy2** [comment]
I think the reply is predictable here. Not the task for a linuxaudio session manager. 

Right click on the folder gives you option to compress in your file manager. That solves both of your 'problems' 1. and 2.

**Comment by falkTX** [comment]
huh, how does that solve anything.
for point 1, you require the user to know that he can not use zip files. this is not explained anywhere, is it?
for point 2, how do you reduce the chances of the user zipping the wrong folder?

I know you want to defend NSM, but if you go discarding suggestions to improve user experience, NSM will end up with no users at all, less than what it has right now.

**Comment by grammoboy2** [comment]
Point 1. You're right. But you can put that in the manual/wiki/tips&tricks.

Afaik it's common practice on Linux to use tar.gz and not zip. At least
that is what my file manager (lxde) is offering me as default option for
compression. If someone uses zip, he will find out it is not working as
it should soon enough. I think it's common practice to test your backup
first, before deleting the original files. 

Point 2. Sorry man, but if you need to help a user to compress the right
folder... come on. There's a limit in how far you should go by assisting
users. This is crossing that limit imho.

I just give my point of view, in this moment of time, that's all.

I don't see why I would need this feature as a nsm user. I don't see how
this feature improves the user experience of nsm significantly.

For myself I just have 3 feature requests to improve the nsm experience,
apart from having nsm support in as much as apps as possible:

1) Make it possible to remove sessions from list in GUI. This makes it
more easy to reach for nsm every time you want to do something with
linuxaudio, also if you just want to test a new application.
https://github.com/original-male/non/issues/273

2) Add shortcut 'a': https://github.com/original-male/non/issues/267

3) Change client names: https://github.com/original-male/non/issues/239

Feel free to have a different opinion.

**Comment by falkTX** [comment]
This whole discussion is very sad.
You have your point of view and are trying to defend it so much as if it was absolute truth and there is no need for anything else.

I mentioned 2 examples on why this (ticket) would be a nice thing to have.
And still, for the sake of user experience, can't we say it is that way.
Your file manager might prefer to use tars for compressing files, but there are many of them out there. You are assuming all of them either 1. have this option to begin with and 2. do things the way you expect. While not a big stretch to think most file managers will behave this way, it is also not a certainty. We can very likely also have one that prefers zip by default, as it might want to have OS interoperability first (Windows, which most people use, will not open zip files by default)

You are not seeing the whole picture in the point number 2.
Perhaps I could further explain why?
Personally I am terrible at naming things, and do a lot of experimental projects just to see if an idea could work. There is even a ticket on this tracker regarding deleting projects from NSM UI, because experimenting with things is a natural tendency for some of us.
So, if we are experimenting, we will name things in a more random way, as it is a test anyway.
I expect after a few experiments to have multiple "test-123" and similar named projects.
Now, one of these projects can actually end up sounding nice, so we want to keep working on it.
Thing is... there are many projects out of the our experimentation that are named very similar to the good one.
If we ever need to export that project to use in a different PC, I would be quite lost. have to make sure the project name matches exactly the folder name.
I might be in a hurry to do such export one day too. So in this case, I would have to manually open my tests projects until I find the right one, and then memorize that name for the tarball compresssion.

Instead, what I hope could be done in this case, is for me use the NSM UI to load a project and verify I have the right one, and then from there directly export it.
Bonus points for having a way to import the exported tarball directly from NSM UI.
When doing this, NSM can actually detect if a needed application/binary is missing for us, and give a warning.


My entire point is, making the software easier to use is a great thing.
People will be happy with it instead of frustrated or confused.
There is no need to mouth-feed users, but the age of users that know deeply how a PC works is long gone. At the moment, with the current NSM UI, it feels more that way.
If we improve it, more people will use it.
We do not have to make/add things in such a way that "power users" will feel repelled. It is not dumbing-down the system, just making it more accessible.


The other points you mention about improving are NSM all valid, but they do not invalidate this one.
We don't have to close this (ticket) idea in order for those to become possible.
Let's leave ticket #240 for discussing the export option, and then other topics in their own tickets, is that okay?

**Comment by grammoboy2** [comment]
Imho there is nothing sad about this discussion. It's simply a feature request by diovudau, with a comment by myself, to discuss this feature with him. I'm just a user, not the developer. You take my opinion way to serious it seems.

**Comment by original-male** [comment]
The problem with features like this from my perspective is that they're kind of vague and open ended. What if the user wants to give special options to tar? What if they are one of these 7z nuts rather than preferring gz? Personally, I don't even use tar, or any archive format for porting sessions: I use rsync! On top of that, we're obviously trying to put a (probably crappy) skin on existing OS features, which always seems silly. I do all file management on the command line because I don't like the crappy skins that most graphical file managers provide over the process. Also, there is a bit of semantic ambiguity around the word "export". How should the user know that "export" means create a portable session and not e.g. to do a freewheeling export of mixed-down audio? There's a big pile of UX/Documentation work there just to explain that.

We always have to ask, how much of users' time is a feature really going to save, and is it worth all of the developer time that's doing to go into implementing a feature.

**Comment by falkTX** [comment]
We know what export means in this case, though it is not a good term, that is a good point.
We can always come up with a better one.



> We always have to ask, how much of users' time is a feature really going to save, and is it worth all of the developer time that's doing to go into implementing a feature.

It is a good question. Personally I think for this specific case, it is worth it.
Since the implementation is not that complex, it will save some headaches for users.
Everytime I need to use rsync, I have to spend some minutes reading the manual to make sure I am doing the right thing...

**Comment by diovudau** [comment]
As all these things, it is a matter of UI design, documentation and labeling.
I am personally willing to let this matter rest for a bit.

**Comment by original-male** [comment]
One aspect of having this as a feature that could be useful is that, if communicated via the NSM protocol to the clients, it could give clients an opportunity to internalize their symlinks or references to files outside of the project dir (non-timeline, for example, has the import-external-sources script to do this). But of course that's really only helpful if all clients that require that actually implement it.

Rsync is a great example of something notoriously difficult to great a usable GUI frontend for...

I think maybe there's a more general convenience feature underlying this request. Maybe something like a list of scripts, that the user can add to, with some build ins, and a Run Script option in the GUI. Examples would be this session bundle thing, maybe git-init and git-commit, that kind of thing. That would allow all this kind of stuff to be implemented as simple shell scripts and not bloat the application itself.

I feel like bundling sessions is a power user thing anyway though. Some stuff is just impossible to make easy. E.g. the multi-machine sessions setup. Or even just having a valid hostname in your network config so that liblo will work at all.

**Comment by grammoboy2** [comment]
Why should a export option "does the tar -h thing" ? Wouldn't it be (also) useful to have a export function that does save a session with a other name, without the tar -h thing?
