### ISSUE TITLE
Non Build Instructions are Incomprehensible. 

### ISSUE THREAD

**Issue by zipzit** [original-male/non#286]
This is pretty frustrating.  I'm looking at [readme](https://github.com/original-male/non)

> Non-things build instructions
This repository contains all of the non-* software.

> Getting NTK
If you just cloned the non repository or just executed git pull, then you should also run

> `git submodule update –init`

> to pull down the latest NTK code required by Non. Git does not do this automatically.

Huh?  I'm confused.  From [this page](https://non.tuxfamily.org/wiki/Requirements), I see there are required dependencies.  

Question #1)  Are those dependencies required to be installed before one attempts to build the entire package, or are those tools installed automatically as part of the non repo install process?

---Attempt #1---------------------------------------------------------------------------------
From the info above it looks like the steps are: 
1)` $   git clone https://github.com/original-male/non.git`
2) `$   git submodule update -init    `   

Total fail, `$ git submodule update -init ` 
`fatal: not a git repository (or any of the parent directories): .git`

Lets try a different tack. Lets assume the writer of the readme erroneously placed the paragraph 
**Building NTK** after **Getting NTK**.  Hint, the number one comes BEFORE the number two.  

> Building NTK
> If you don’t have NTK installed system-wide (which isn’t very likely yet) you MUST begin the build process by typing:

> `cd lib/ntk ./waf configure ./waf`

> Once NTK has been built you must install it system-wide before attempting to build the non-* programs.

> To install NTK type: `su -c ‘./waf install’`

---Attempt #2--------------------------------------------------------------------------------
1) `$   git clone https://github.com/original-male/non.git`
2) `$   cd lib/ntk ./waf configure ./waf`  
    first attempt = fail:  `$ cd lib/ntk ./waf configure ./waf`
`bash: cd: too many arguments`
    second attempt = fail `$ cd non/lib/ntk ./waf configure ./waf`
`bash: cd: too many arguments`
     third attempt = fail `$ cd non/lib/ntk ./waf
`bash: cd: too many arguments`
     fourth attempt = `$ cd non/lib/ntk`
     followed by  `$  ./waf configure ./waf` = fail
 `bash: ./waf: No such file or directory`
     last attempt here:  :~/non/lib/ntk$ `./waf`
`bash: ./waf: No such file or directory` = fail.

---Attempt #3-------------------------------------------------------------------------------

Lets just ignore the readme for a moment.   I see elsewhere [instructions for installing NTK](http://non.tuxfamily.org/wiki/NTK) 

> Downloading
To access the NTK source code directly, use the command:

> `git clone git://git.tuxfamily.org/gitroot/non/fltk.git ntk`

clone works well, then $ `cd ntk`
Oops.  $ `su -c ‘./waf install’` total fail:  `su: user install’ does not exist`

I give up.  This may be a great program, with lots of time spent on its creation, but I have no clue on how to install it.   The readme on the github page isn't much help.    Oh, and its totally possible I'm using the wrong operating system. (It would be helpful if that information was included somewhere...)    

 ```
$ hostnamectl 
 Operating System: Ubuntu 20.04 LTS
 Kernel: Linux 5.4.0-31-generic
 Architecture: x86-64`
```
And if I've done this wrong, profuse apologies.  In my defense, I'm only following written instructions.  

Anybody else having installation woes here?

**Comment by grammoboy2** [comment]
On 6/1/20 3:26 AM, Zip wrote:
> |git submodule update –init|

You have to use two dashes


git submodule update --init

**Comment by zipzit** [comment]
Right you are... and in fact I COPIED THAT COMMAND DIRECTLY FROM [THE README.MD FILE](https://github.com/original-male/non), where it copies and pastes as:  

`git submodule update –init     #single dash before init`

So, yes, when the readme instructions on the home page lead you down a rabbit hole, I would confirm the instructions are unusable.  But apparently, someone already picked up on this and created a pull request with a fix.  (Not sure why there wasn't an open issue for it... I checked before I pulled this one...)  

See https://github.com/original-male/non/pull/282
and the pull request fix at https://github.com/theGreatWhiteShark/non/tree/readme-update (reported on 26 April 2020)  

Today is 11 Jun 2020.. Its a pretty simple pull request, with a likelihood of zero for merge compatibility troubles.  Huh?  What am I missing?   I'm assuming this issue can be closed when the pull request is actually merged to master.  

Or is this a subtle statement telling me that Non isn't the Digital Audio Workstation for me?  This is too frustrating.

**Comment by grammoboy2** [comment]
On 6/12/20 4:55 AM, Zip wrote:
>
> Or is this a subtle statement telling me that Non isn't the Digital 
> Audio Workstation for me? This is too frustrating.
>
Try ardour (ardour.org)
>

**Comment by jrigg** [comment]
> I COPIED THAT COMMAND DIRECTLY FROM THE README.MD FILE

That's where you went wrong ;-)

Github README.md files are often incorrect due to weird rendering. Worse, the README.build file contains the correct instructions when you read the actual text file, but Github renders it incorrectly on the web page. A source code repository interface that doesn't render text files correctly seems crazy to me, but someone obviously thought it was a good idea.

It's always a good idea to check README text files in a text viewer rather than rely on the broken Github text rendering.

**Comment by falkTX** [comment]
Github uses markdown, which is well established by now.
If the README does not have .any file extension at the end, it will not be parsed as mardown and shown as clear text.
Since the project author @original-male was the one that put up the project on github, I think it is fair to ask to ensure the readme is rendered correctly.

**Comment by zipzit** [comment]
Followup. It's now been 11 weeks since 26 April 2020, and the submission of a pull request fix for this open issue.  That seems excessive for a simple fix.

**Comment by falkTX** [comment]
you will likely have better chances using https://github.com/linuxaudio/new-session-manager.
'non' author does not really reply to tickets anymore, unless it is to complain and rant about something :/

**Comment by grammoboy2** [comment]
On 7/14/20 9:09 PM, Filipe Coelho wrote:
>
> you will likely have better chances using 
> https://github.com/linuxaudio/new-session-manager.
> 'non' author does not really reply to tickets anymore, unless it is to 
> complain and rant about something :/
>
This disrespect is beyond anything. It's sad you don't realize. Just 
fork a project, or even more important a idea, and have nothing but 
disrespect for the original author. It's a shame. You might better just 
reply on your own project page.

**Comment by falkTX** [comment]
I am not the one realizing how sad it is?
How about 

> Fuck you you pathetic fucking hack. You're a worthless piece of shit

A quote from your very own dear NSM maintainer.

I posted here a bit out of frustration, deleted it shortly afterwards after being advised of doing so.
We really want to make what is best for NSM and push it forward. It was/is simply not working out with the current maintainer.

**Comment by grammoboy2** [comment]
On 7/14/20 11:42 PM, Filipe Coelho wrote:
>
> I posted here a bit out of frustration, deleted it shortly afterwards 
> after being advised of doing so.
> We really want to make what is best for NSM and push it forward. It 
> was/is simply not working out with the current maintainer.
>
Then follow up that advise for a second time.

You show little sensitivity here. Well written patches would have been 
accepted, you know that. Suddenly it is possible to write patches since 
the fork, that's a bit strange isn't it? There where other ways to 
organize a fork or change maintainer-ship. But you didn't want to see 
them. I've told you and Nils, but you had to laugh about my responses to 
your fork suggestion via e-mail. Maybe you've the coding skills, but you 
seems to lack visionary skills. Seeing the thing as a whole and then 
make wise decisions. Thank you for ditching the original developer with 
his ideas and skills for us in all your wisdom.

Your goal was a fork anyway most likely. Congratulations, you got Nils 
that far now. You're free to do with it what you like now. Implementing 
it in Carla and stuff that's beyond the scope of NSM. You backed up 
Ladish all the way, implementing it in your software, until you realized 
that NSM wasn't that bad maybe, which took you quite some time. Now you 
want to use NSM for it and even put your name on it (and we can just 
pray you don't make it a Ladish 2.0).

Anyway, just don't forget that you nor Nils didn't design nor write NSM. 
A little bit respect and being a bit more humble wouldn't be bad at all 
I think.

**Comment by mxmilkiib** [comment]
Suddenly it's possible to have patches accepted after the fork. I suggest you are hypermentalising and splitting, please go research that, related subjects, and attachment theory. Please stop escalating things, it's not good for anyone's mental health.

**Comment by falkTX** [comment]
sigh, you always bring stuff that is unrelated to the topic at hand. Wherever I add NSM inside carla as a test to run applications as plugins is completely irrelevant. I have SIGUSR1 support in there too. This has been slowly in the works since 2017, it is not recent. See for yourself that it says 2017 https://github.com/falkTX/Carla/commit/0584579c1645a894d1f50f60669a0163cab61c19#diff-1946e7933ec1d72f52a4f5e917b0bd14

> You show little sensitivity here. Well written patches would have been accepted, you know that

I certainly know it is not the case, and you are being disingenuous by saying that.
You know that for a fact to be false. Please don't lie. If you truly believe that to be the case, then this is all pointless as there seems to be some reality checks needed first before anything else.


> I've told you and Nils, but you had to laugh about my responses to your fork suggestion via e-mail

We are not laughing, this is a very sad state of affairs we got ourselves into.
We really feel that NSM was simply being left to die, and it is because we like it and want to make more widespread that we forked. How hard is this to understand? At this point, if you insist anymore, I just have to assume you are trolling.



> And don't pretend it's the good guys vs the bad guy.

This has never been good vs bad guy, so there is no pretending going on, it is not a thing that is happening.

> You've your personal interests in a fork and you just have it the way you want it now,

Our **collective** (not personal) interest is to see a good SM actually become something we can use.
We are pushing ourselves to implement NSM in a better way actually:
1. fixing bugs that were in the server implementation from the very start (due to lack of testing I assume)
2. fixing our own applications to handle NSM better (new carla release has optional-gui and proper handle of multi-client)
3. adding more applications that entirely revolved around NSM (I started that "carla plugins inside NSM" project you so wanted already, but it is going to be a separate project, though still using carla in the background)
4. encouraging other developers to add NSM support (jack-mixer is being revived and brings NSM support, a jack-keyboard tool has been created by brummer10 which has NSM support too)


> don't pretend you're 'mister social'.

This is off-topic, but if I family read this, they would have a serious laugh :D
I will take this as a compliment, my social skills are good enough that I receive that remark somehow, thanks.

> This whole fork (which could have been a change of maintainer-ship probably) could and should have been done in a more classy and wise manner.

If the original developer was not so much filled with anger, this could have happened yes.
I have taken maintenance of quite a few other projects just fine before... dssi-vst, jack and recently wineasio.
The only time I received similar responses to this that I recall (mildly in comparison) was when I publicly stated my disapproval of JUCE's use of analytics. It was mostly bashing me for how idiotic and naive I was being, apparently.

PS: Sorry I lit up the fire here again everyone. Better to keep mouth shut next time.

**Comment by grammoboy2** [comment]
On 7/15/20 2:05 AM, Filipe Coelho wrote:
>
>     You show little sensitivity here. Well written patches would have
>     been accepted, you know that
>
> I certainly know it is not the case, and you are being disingenuous by 
> saying that.
> You know that for a fact to be false. Please don't lie. If you truly 
> believe that to be the case, then this is all pointless as there seems 
> to be some reality checks needed first before anything else.
>
There was one bug report by the raysession author. He just reported it, 
no patch to fix it. Now there is a patch by him for new-session-manager.

Nils had written two patches recently for NSM. One got accepted and one 
rejected with good argumentation.

You can't just say that people lie.

**Comment by jrigg** [comment]
Nobody seems to have noticed that the offending line in the Readme.md file shows a long dash (ie. double dash in ASCII) in front of 'init'. It's a very bad idea to copy and paste a command line from an HTML page because of rendering quirks like this. This whole thread was over nothing :-)
